version: '3'
services:
  vacation-request-postres-db:
    container_name: vacation-request-postres-db
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
    networks:
      - backend-network
  employee:
    build: ./employee-module
    ports:
      - "8081:8081"
    depends_on:
      - vacation-request-postres-db
    networks:
      - backend-network
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

networks:
  backend-network:
    external: false